const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Multiplayerevents_Event1_Act2,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.EightDir.Acts.SetDefaultControls,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.JavaScriptInEvents.Menuevents_Event1_Act1,
		C3.JavaScriptInEvents.Menuevents_Event2_Act1,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{Vi: 0},
	{"8Directions": 0},
	{ChercheChemin: 0},
	{Cat: 0},
	{Mouse: 0},
	{Player1Score: 0},
	{Clavier: 0},
	{JouerJoueur: 0},
	{JouerRobot: 0},
	{BoutonRetour: 0},
	{MouseSpawner: 0},
	{CatSpawner: 0},
	{NightmareButton: 0},
	{NightmareCat: 0},
	{DéfilerVers: 0},
	{NightmareMouse: 0},
	{Sinus: 0},
	{Light: 0},
	{Solide: 0},
	{Wall: 0},
	{Audio: 0},
	{CatTime: 0},
	{PLayer2Score: 0},
	{Cheese: 0},
	{Manche: 0},
	{Score1: 0},
	{Score2: 0},
	{Joueur1: 0},
	{Joueur2: 0},
	{Chesse: 0},
	{text: 0},
	{Temps: 0}
];

self.InstanceType = {
	Cat: class extends self.ISpriteInstance {},
	Mouse: class extends self.ISpriteInstance {},
	Player1Score: class extends self.ITextInstance {},
	Clavier: class extends self.IInstance {},
	JouerJoueur: class extends self.IButtonInstance {},
	JouerRobot: class extends self.IButtonInstance {},
	BoutonRetour: class extends self.IButtonInstance {},
	MouseSpawner: class extends self.ISpriteInstance {},
	CatSpawner: class extends self.ISpriteInstance {},
	NightmareButton: class extends self.IButtonInstance {},
	NightmareCat: class extends self.ISpriteInstance {},
	NightmareMouse: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	CatTime: class extends self.ITextInstance {},
	PLayer2Score: class extends self.ITextInstance {},
	Cheese: class extends self.ISpriteInstance {}
}